config/routes.rb
Rails.application.routes.draw do
  get 'welcome/home'
  root "welcome#home"

  get '/signup', to: "users#new"
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
  resources :users, except: [:new, :destroy]

  resources :orders, only: [:index]
  resources :order_products, only: [:index]

  resources :products, only: [:index] do
    collection do
      get 'sold'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  # associations
  has_many :category_products
  has_many :products, through: :category_products

  # validations
  validates :title, presence: true,
                    uniqueness: true,
                    length: { minimum: 3, maximum: 25}
end

app/models/category_product.rb
class CategoryProduct < ApplicationRecord
  belongs_to :category
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  before_save { self.status = "on its way"}

  # associations
  belongs_to :user
  has_many :order_products
  has_many :products, through: :order_products

  # validations
  validates :user_id, presence: true

  def total
    self.products.reduce(0) { |sum, product| sum + (product.price * product.quantity) }
  end

  def self.created_between(start_date, end_date)
    where("created_at >= ? AND created_at <= ?", start_date.to_date, end_date.to_date)
  end
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  # associations
  has_many :order_products
  has_many :orders, through: :order_products

  has_many :category_products
  has_many :categories, through: :category_products

  # validations
  validates :name, presence: true,
                   length: { minimum: 3, maximum: 25}
  validates :quantity, presence: true
  validates :price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # before callbacks
  before_save { self.email = email.downcase }

  # associations
  has_many :orders, dependent: :destroy
  has_many :products, through: :orders

  # validations
  validates :username, presence: true,
                       uniqueness: { case_sensitive: false},
                       length: { minimum: 3, maximum: 15 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    length: { maximum: 100 },
                    uniqueness: { case_sensitive: false },
                    format: { with: VALID_EMAIL_REGEX }

  validates :first_name, presence: true

  validates :password, presence: true, length: { minimum: 5 }, allow_nil: true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  # returns the currently logged in user
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  # checks if the user is logged_in?
  def logged_in?
    !!current_user
  end

  # sets the flash and redirects to root path if user not logged in
  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end
end

app/controllers/order_products_controller.rb
class OrderProductsController < ApplicationController
  def index
    order = Order.find_by(id: params[:order])
    @products = order.products
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :require_user

  def index
    @orders = current_user.orders.paginate(page: params[:page], per_page: 2)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :require_admin, only: [:sold]

  def index
    @products = Product.all.paginate(page: params[:page], per_page: 5)
  end

  def sold
    if params[:products_sold].present?
      @start_date, @end_date, @option = params[:products_sold][:from],
                                        params[:products_sold][:to],
                                        params[:products_sold][:option]

      if @start_date.present? && @end_date.present? && @option.present?
        # returns all the orders created within a time range
        orders = Order.created_between(@start_date, @end_date)

        if !orders.empty?
          # groups orders by selected option -> day/week/month
          sold_orders_by_option = sold_orders_by_option(orders, @option)
          # returns all the products for orders
          @sold_products = get_products_for_orders(sold_orders_by_option)
        else
          flash[:danger] = "No orders for this time duration"
          redirect_back(fallback_location: root_path)
        end
      else
        flash[:danger] = "Start date, End date or Option invalid"
        redirect_back(fallback_location: root_path)
      end
    end
  end


  private

  def sold_orders_by_option(collection, option)
    if !(collection.empty?) && !option.empty?
      if option == 'Day'
        return collection.group_by_day { |order| order.created_at }
      elsif option == 'Week'
        return collection.group_by_week { |order| order.created_at }
      else
        return collection.group_by_month { |order| order.created_at }
      end
    end
  end

  def get_products_for_orders(orders)
    products = orders.reduce({}) do |result, (key,values)|
      result[key] = values.map(&:products).flatten
      result
    end
    products_hash = convert_object_to_attributes(products)
    combine_quantity_for_duplicate_products(products_hash)
  end

  def convert_object_to_attributes(products)
    products.reduce({}) do |result, (key,values)|
      result[key] = values.map { |p| {"#{p.name}" => "#{p.quantity}"} }
      result
    end
  end

  def combine_quantity_for_duplicate_products(products)
    products.reduce({}) do |result, (key, products_array)|
      products_array = products_array.inject() do |memo, product|
        memo.merge(product) { |k, old_v, new_v| old_v.to_f + new_v.to_f}
      end
      result[key] = products_array
      result
    end
  end

  # checks if the user is an admin
  def require_admin
    if !logged_in? && !current_user.admin?
      flash[:error] = "You must be an admin to perform that action"
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have succesfully logged in"
      redirect_to products_path
    else
      flash[:danger] = "Email or Password invalid"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have successfully logged out. Thank you for shopping. See you soon!"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy, :show]
  before_action :require_user, only: [:edit,:update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome #{@user.username}!"
      redirect_to products_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Your account was updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
  def set_user
    @user = User.find_by(id: params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :username, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_flash.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= msg %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="navbar-default navbar-fixed-bottom footer">
  <div class="container-fluid">
    <span><a href="https://www.linkedin.com/in/ssachid/">Linkedin</a><span>
    <span><a href="https://github.com/ssachid">Github</a></span>
    <span class="name">Shambhavi Sachid</span>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "SHIPT", welcome_home_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "My Orders", orders_path, id: "nav1" %><span class="sr-only">(current)</span></li>
        <li class="dropdown">
            <a id="nav1" href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Products<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "View All Products", products_path %></li>
              <% if logged_in? && current_user.admin? %>
                <li><%= link_to "Sold Products", sold_products_path %></li>
              <% end %>
            </ul>
        </li>

      </ul>
      <ul class="nav navbar-nav navbar-right">
      <% if logged_in? %>
        <li class="dropdown">
          <a id="nav1" href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %> <%= "| Admin" if current_user.admin? %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "View your Profile", user_path(current_user) %></li>
            <li><%= link_to "Edit your Profile", edit_user_path(current_user) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Log out", logout_path, method: :delete %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "Log in", login_path, id: "nav1" %></li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShiptCodingChallenge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navigation" %>
    <%= render "layouts/flash" %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/orders/_order_products.html.erb
<tr>
  <% obj.each do |product| %>
    <td><%= image_tag(product.image, :size => "50x50", class: "img-circle avatar avatar-original", style: "-webkit-user-select:none;
              display:block; margin:auto;" ) %></td>
    <td><%= product.name %></td>
    <td><%= product.quantity %></td>
    <td><%= product.price %></td>
  </tr>
<% end %>

app/views/orders/index.html.erb
<%= render 'shared/page_title', title: "My orders" %>
<div align="center">
  <%= will_paginate @orders%>
    <% @orders.each do |order| %>
      <div align="center" class="well">
        <div class="col-md-4"><strong>Order Id: </strong><%= order.id %></div>
        <div class="col-md-4"><strong>Order Placed: </strong> <%= time_ago_in_words(order.created_at).capitalize %> ago</div>
        <div class="col-md-4"><strong>Order status: </strong> <%= order.status.capitalize %></div>
        <hr />
        <% if order.products.any? %>
          <table class="table table-striped">
            <thead>
              <tr>
                <th>Product Image</th>
                <th>Product Name</th>
                <th>Product Quantity</th>
                <th>Product Price/Unit</th>
              </tr>
            </thead>
            <tbody>
              <%= render 'order_products', obj: order.products %>
              <td colspan = "3"><strong>Total</strong></td>
              <td><strong>$ <%= order.total %></strong></td>
            </tbody>
          </table>
        <% else %>
          <p class="badge">No products in this order</p>
        <% end %>
      </div>
      <hr>
    <% end %>

  <%= will_paginate @orders%>
</div>

app/views/products/_products.html.erb
<% obj.each do |product| %>
  <div class="row">
    <div class="col-md-2">
      <section class="center">
        <%= image_tag(product.image, :size => "160x160", class: "img-circle avatar avatar-original", style: "-webkit-user-select:none;
              display:block; margin:auto;" ) %>
      </section>
    </div>
    <div class="col-md-8 well">
      <h4><%= product.name %></h4>
      <p>$ <%= product.price %>/unit</p>
      <p><%= truncate(product.description, length: 300) %>/unit</p>
      <% if logged_in? %>
          <% if current_user.admin? %>
            <div class="product-actions">
              <%= link_to "Edit this product", '#', disabled: true, class: "btn btn-xs btn-warning" %>
              <%= link_to "Delete this product", '#', disabled: true, method: :delete,
                                                data: { confirm: "Are you sure you want to delete this product?" },
                                                class: "btn btn-xs btn-danger" %>
            </div>
          <% end %>
          <div class="product-actions pull-right">
            <%= link_to "Add to Cart", '#', disabled: true, class: "btn btn-sm btn-primary" %>
          </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/products/index.html.erb
<%= render "shared/page_title", title: "showing all products" %>

<div align="center">
  <%= will_paginate %>
</div>
<%= render 'products', obj: @products %>
<div align="center">
  <%= will_paginate %>
</div>

app/views/products/sold.html.erb
<div align="center">
  <h4>Enter a date range and a day, week, or month to receive a breakdown of products sold by quantity per day/week/month.</h4>
  <hr>
  <%= form_for :products_sold, :html => { class: "form-inline"}, url: sold_products_path, method: :get do |f| %>
    <%= f.label :from, class: "sr-only" %>
    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
      <%= f.text_field :from, class: "form-control datepicker", id: "inlineFormInputGroup", placeholder: "From" %>
    </div>

    <%= f.label :to, class: "sr-only" %>
    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
      <%= f.text_field :to, class: "form-control datepicker", id: "inlineFormInputGroup", placeholder: "To" %>
    </div>

    <div class="input-group">
      <%= f.label :option, class: "input-group mr-sm-2" %>
      <%= f.select :option, ['', 'Day', 'Week', 'Month'], class: "custom-select mb-2 mr-sm-2 mb-sm-0", id: "inlineFormCustomSelect", placeholder: "Choose.." %>
    </div>

    <div class="input-group">
      <%= f.submit 'Submit', class: "btn btn-primary"%>
    </div>
  <% end %>
</div>
<hr>

<% if @sold_products %>
  <span><h4 class="col-md-10 color" align="center">Products sold by <%=@option%> between <%=@start_date %> and <%= @end_date %> </h4></span>
  <span class="csv col-md-2 pull-right"><%= table_export_tag('sold_products',{export_link_text: 'Export to CSV', width: '120px', height: '40px', color: '#fff', bgcolor: '#2e6da4'})%></span>
  <div align="center">
      <table id="sold_products" class="table table-striped table-responsive">
        <thead>
          <tr>
            <th class="timestamp" rowspan=2>Timestamp</th>
            <th colspan=2>Product Details</th>
          </tr>
          <tr>
            <th>Product Name</th>
            <th>Product Quantity</th>
          </tr>
        </thead>
        <tbody>
          <% @sold_products.each do |timestamp, products| %>
            <td rowspan="<%= products.count + 1%>"><%= timestamp %></td>
            <% products.each do |key,value| %>
            <tr>
              <td><%= key %></td>
              <td><%= value %></td>
            </tr>
            <% end %>
          <% end %>
        </tbody>

      </table>
  </div>
<% end %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>
            prohibited this <%= obj.class %> from being saved:
          </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_page_title.html.erb
<h1 align="center"><%= title.capitalize %></h1>
<hr />

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
<div class="row">
  <div class="col-md-12">
    <%= form_for(@user, :html => {class: "form-horizontal", multipart: true, role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :first_name, "Enter your First Name" %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :first_name, class: "form-control", placeholder: "Enter your user name", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :username, "Choose Username" %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :username, class: "form-control", placeholder: "Enter your user name", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :email %>
        </div>
        <div class="col-md-8">
          <%= f.email_field :email, class: "form-control", placeholder: "Enter your email" %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :password %>
        </div>
        <div class="col-md-8">
          <%= f.password_field :password, class: "form-control", placeholder: "Choose a Password" %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :password_confirmation, "Confirm Password" %>
        </div>
        <div class="col-md-8">
          <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm password" %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit( @user.new_record? ? "Create my account" : "Update my account", class: "btn btn-primary btn-lg btn-color") %>
        </div>
      </div>
    <% end %>
    <div class="col-md-4 col-md-offset-4 colormatch">
      [ <%= link_to "Cancel request and return to home page", welcome_home_path %> ]
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<%= render 'shared/page_title', title: "Edit your Profile" %>
<%= render 'form' %>

app/views/users/new.html.erb
<%= render 'shared/page_title', title: "Sign up for the application" %>
<%= render 'form' %>

app/views/users/show.html.erb
<br>
<div class="container">
  <div class="row">
    <div class="col-md-9 centering">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="row">
            <div class="col-md-12 lead">Your profile<hr></div>
          </div>
          <div class="row">
      <div class="col-md-4 text-center">
              <img class="img-circle avatar avatar-original" style="-webkit-user-select:none;
              display:block; margin:auto;" src="http://robohash.org/sitsequiquia.png?size=120x120">
            </div>
            <div class="col-md-8">
              <div class="row">
                <div class="col-md-12">
                  <h1 class="only-bottom-margin"><%= @user.first_name.capitalize %></h1>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <span class="text-muted">Email:</span> <%= @user.email %><br>
                  <small class="text-muted">Created: <%= time_ago_in_words(@user.created_at) %></small>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <hr><%= link_to edit_user_path(current_user), class: "btn btn-default pull-right" do %>
                <i class="glyphicon glyphicon-pencil"></i> Edit
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/welcome/home.html.erb
<div class="jumbotron">
  <% if current_user %>
    <h2 align="center" class="display-3">Hello <%= current_user.first_name.capitalize %>!</h1>
  <% end%>
  <h2 align="center" class="display-3">Welcome to Shipt online grocery service!</h1>
  <hr class="my-4">
  <p></p>
  <% if logged_in? %>
     <p align="center" class="lead">
      <%= link_to "Look up Products", products_path, class: "btn btn-danger btn-lg btn-xlarge" %>
    </p>
  <% else %>
    <p align="center" class="lead">
      <%= link_to "Sign up", signup_path, class: "btn btn-danger btn-lg btn-xlarge" %>
    </p>
  <% end %>
</div>